### ISSUE TITLE
Hubic token expiration

### ISSUE THREAD

**Issue by tounefr** [ovh/svfs#30]
Hi,

I would like to Dockerize svfs to backup my datas to Hubic.
So, i plan to create a Python script to automate the process to get the token access from the Hubic API.
After the token expiration, is the container auto unmounted even if data are being transfered ?
Is svfs auto exited when the token expired ?
Have you planned to address the limitation of 24h expiration ?
How to use svfs with an Hubic application ? 

Thanks !

**Comment by xlucas** [comment]
Hello !

When the token expires, previously triggered operations will end up normally except large transfers implying the creation of segments (since it means sending multiple requests to the swift endpoint).
The filesystem is not unmounted, but all future operations will end up with I/O errors.

We plan to address this 24h limit and are currently discussing the best way to do this (probably by supporting hubic oauth or by exposing a standard identity endpoint).

**Comment by tounefr** [comment]
Is there a way to call an external python script by svfs when the token expires ?

**Comment by xlucas** [comment]
Unfortunately, there's no way to do this for now. You need to remount svfs every 24h when used with hubic.

I'm currently working on a workaround in svfs using a user-declared hubic application and new options. Even though we may change the way token is refreshed later, this would allow to quickly overcome this limit in the meantime.

**Comment by xlucas** [comment]
You may be interested by the [hubic_token](/ovh/svfs/tree/hubic_token) branch, it's currently experimental and brings support for automatic token refresh with hubic.

**Comment by tounefr** [comment]
Nice ! I hope for the next release version !

**Comment by xlucas** [comment]
Release 0.5.0 is out !

**Comment by tounefr** [comment]
Great ! I test this :)
