### ISSUE TITLE
upload large file fail on swift

### ISSUE THREAD

**Issue by supnobita** [ovh/svfs#54]
Hi xlucas,
Thanks for your software. It's great work :)
I have use it for mounting swift as local file system on my server (/mnt).
I install PureFTP on that server and create ftp account that have home directory is /mnt/container . But when i set segment_size=4200 (4G) and upload large file it fail. When client upload object at 4200MB, the FTP server return 500 unknow command. (pureftp support large file, i tested on local disk). Have you know what happen with this error ?

**Comment by xlucas** [comment]
Hello and thanks :)

Are you using a vanilla swift endpoint or hubic ?
Can you explicitly detail your mount options (without credentials) ?

**Comment by supnobita** [comment]
Hi lucas,
Sorry for reply so late :)
I build a openstack swift on my own server to use as storage cluster. We use web app to connect swift and access data.
My boss need connect swift storage via FTP, i find your software svfs. My solution is: build a pure-ftp server and use svfs mount swift container as a mount point. I create a new ftpuser and change home directory of FTP user = mount point.
 mount -t svfs -o identity_url=http://controller:5000/v2.0,username=xx,password=xx,tenant=demo,region=regionOne,allow_other=true,uid=1001,gid=1001,umask=0022,mode=0770,segment_size=4100 pcs /home/ftpuser/cloud

I upload many small file < 1G is OK. But when I upload a big file >4100M. FTP client fail to upload (filezila). When client upload until 4100M, ftp server respone a 500 error, and no data can upload any more => fail
When i remount with option segment_size=1025, i can upload a FIle > 5G without error. I think may be when svfs create a setment file  on swift, it delay so long and the FTP server think this file is write fail ?

**Comment by supnobita** [comment]
I also think when my user who has slow internet, they can fail when they upload file > 1G because this error !

**Comment by xlucas** [comment]
Hello,

In order to handle segmented objects, svfs always upload data in the base container at first, as if it was a non-segmented object, then moves it to the segment container when the overall uploaded size reaches `segment_size`. After this, remaining data will be appended as successive segments and finally the manifest is created.

In order to move this data (i.e. the first segment), svfs orders a `COPY` operation from the base container to the segment container, followed by a `DELETE` operation to clear the base container. All of this happens **server-side**, so the bigger the segment size, the longer this whole operation will take.

My guess is that your storage performance is insufficient to see these operations complete before a write timeout is triggered in the FTP server. You should tailor `segment_size` in order to fit your setup and avoid hanging on large sequential read or writes for too long. Start with the default value and increase/decrease it according to your observations.

**Comment by supnobita** [comment]
Hi lucas,

Thanks for your suggestion :)
I'll turning segment_size follow your instruction
