### ISSUE TITLE
space available

### ISSUE THREAD

**Issue by beankylla** [ovh/svfs#56]
Hello and thanks again for solutioning my NASfree home headache! :)

it would be nice to be able to ask how much space is occupied vs free :)

of course, it's a "nice to have".

Thanks and have a nice day!

**Comment by xlucas** [comment]
I think reporting the actual usage for tools like `du` should be the best move. It's been fixed in PR #58

Two things come into play when trying to report usage ratio : 

- I'm not sure if there's a way to trick `df` to report filesystem usage for FUSE filesystems as they are usually seen as dummy filesystems (see `df -a`).
- It's indeed possible to process a usage ratio for hubiC users, but it's not always possible to give such an information : a user may not have a quota set on his swift account (for instance, OVH Public Cloud Storage doesn't limit usage space).

**Comment by xlucas** [comment]
Implemented in 0.6.1

**Comment by beankylla** [comment]
Realllllyyy awesommmme thanks a LOT! Huge improvement (for me at least ^^)!
