### ISSUE TITLE
Rsync errors : symlink and mkstemp

### ISSUE THREAD

**Issue by boscorelly** [ovh/svfs#61]
Hi,

i just get this :

rsync: symlink "/mnt/svfs/hubic/.composer/vendor/bin/.laravel.15610" -> "../laravel/installer/laravel" failed: Input/output error (5)

**Comment by xlucas** [comment]
Hello,

svfs doesn't handle symlinks for now.

This should be documented better.

**Comment by boscorelly** [comment]
Ok thanks. It will be supported later ?

Also, the documentation about svfs and PCS is not good. I was unable to connect to PCS.

**Comment by xlucas** [comment]
It will be.

What is/was your issue with PCS ?

**Comment by boscorelly** [comment]
root@orange:~
# ./openrc.sh
Please enter your OpenStack Password:
root@orange:~
# echo $OS_PASSWORD_INPUT

root@orange:~
# nano openrc.sh
root@orange:~
# ./openrc.sh
root@orange:~
# echo ${OS_PASSWORD}

root@orange:~
# echo $OS_PASSWORD

root@orange:~
# echo $OS_USERNAME

root@orange:~
# mkdir /mnt/GRA1
root@orange:~
# mount -t svfs -o username=$OS_USERNAME,password=$OS_PASSWORD,tenant=$OS_TENANT_NAME,region=$OS_REGION_NAME pcs /mnt/GRA1/
root@orange:~
# 2016/05/21 15:49:25 Bad Request

**Comment by xlucas** [comment]
Well, please don't paste your raw console output, tailor it to the relevant part, it would be easier to read.

So if I read it well, and you are not somehow hiding your actions output, your issue is that your environnement variables are not exported, right ?

**Comment by boscorelly** [comment]
It seems to be that :(

I also just add this error :
`rsync: mkstemp "/mnt/svfs/hubic/.composer/cache/files/symfony/polyfill-mbstring/.624d730be0ea9edd5c8cfeb4aaf5d697d56f706b.zip.IzhuLp" failed: Operation not supported (95)
rsync: mkstemp "/mnt/svfs/hubic/.composer/cache/files/symfony/polyfill-php56/.0b8ec31a480b955b9d3857ce91ffe0e358f4aa18.zip.mfZnbg" failed: Operation not supported (95)
rsync: mkstemp "/mnt/svfs/hubic/.composer/cache/files/symfony/polyfill-util/.ab2b2f259f5533304e6e115a16e5789eb2544a6a.zip.e9X1iP" failed: Operation not supported (95)
`

**Comment by xlucas** [comment]
Ok, so if that's your raw terminal output then it seems normal to me these actions produce what you see : you are *executing* the `openrc.sh` script instead of **sourcing** it. The PCS documentation is fine on this part. The consequence is : you are not exporting environment variables in the current shell process but in a subprocess. Also, you don't need root access, edit `keep_env` in the sudoers file  so you can pass these openstack credentials during mount.

Regarding the last error, this is expected if you use any process opening a file in append mode inside svfs. This is documented in the [limitations section](https://github.com/ovh/svfs#limitations). Particular `rsync` options are required if you synchronize data from/to an svfs mountpoint and these are documented in the [FAQ](https://github.com/ovh/svfs/blob/master/docs/FAQ.md#how-does-it-compare-to-hubicfuse-cloudfuse-swiftfs--). Note that the FAQ also explains modification time change can only be processed when enabling extend attributes (`extra_attr=true`).

If you have further problems, please open a ticket for each kind of issue. This way it's much easier to maintain the project.

**Comment by xlucas** [comment]
See #62 for symlink implementation.

**Comment by xlucas** [comment]
[README](https://github.com/ovh/svfs/#faq) and [FAQ](https://github.com/ovh/svfs/blob/master/docs/FAQ.md#i-got-errors-using-rsync-with-svfs) have been updated.

Hopefully this will bring more attention to properly using `rsync` with svfs.
