### ISSUE TITLE
Webstorage CDN

### ISSUE THREAD

**Issue by ne0ark** [ovh/svfs#94]
### Context
- svfs version : 0.7.4
- storage provider : OVH
- product : Webstorage CDN

### Steps to reproduce this issue :

1.   mount -t svfs -o auth_url="https://lb1047.pcs.ovh.net:5443/v2.0",username="[usernam]",password="[password]",tenant="[tenant]",storage_url="[url]" webstorage /root/webstorage

Credential Information was taken from: https://api.ovh.com/console/#/cdn/webstorage/%7BserviceName%7D/credentials#GET

### Results you expected :
Mount the Openstack Storage

### Results you observed :
Error

### Debug log :
2016/08/31 10:20:00 Bad Request

**Comment by Minims** [comment]
Hi,

Have you tried like this : 

 mount -t svfs -o username="[username]",password="[password]",tenant="[tenant]",identity_url="https://lb1047.pcs.ovh.net:5443/v2.0",container=default cdn /mnt/cdn

**Comment by ne0ark** [comment]
That seems to work. Is there a way to figure out auth_url and region?

**Comment by xlucas** [comment]
Hello,

Two things here : 
- You don't need the `storage_url` option since this is only useful when you don't have explicit credentials (i.e. tenant, username, password etc).
- Check out the documentation from the release branch. Alot of changes have been pushed to master, so there's a diff with the version you are using : for instance `identity_url` option will be changed to `auth_url` in the next release.

**Comment by xlucas** [comment]
@ne0ark `auth_url` is `identity_url` in 0.7.4.
You don't need the `region` option since there's only one with CDN.

But if you are curious, you can list available regions and services like this : 

```bash
curl "https://lb1047.pcs.ovh.net:5443/v2.0/tokens" -H "Content-Type: application/json" -d '
{
    "auth": {
        "tenantName": "[tenant]",
        "passwordCredentials": {
            "username": "[username]",
            "password": "[password]"
        }
    }
}
'
```

**Comment by ne0ark** [comment]
Thank you :) Resolved.
