### ISSUE TITLE
suggestion: add to the limitations section in README.md

### ISSUE THREAD

**Issue by lartaud** [ovh/svfs#99]
Hello.

I would suggest that you add to the “Limitations” that svfs can’t open a file in O_RDWR mode…
(For GO users, it means that you can’t use “os.Create”… Took some time to find the problem ;-p)

Regards.

### Context
- svfs version : 0.8.2
- storage provider : Hubic

**Comment by xlucas** [comment]
Hello :)

Yes `os.Create` will not work.

Just a point of detail : it's not because of `O_RDWR` but `O_TRUNC` ([source here](https://golang.org/src/syscall/syscall_linux.go?s=789:845#L22)).

Anyway, both modes are not handled by SVFS and I recognize the "append mode" formulation may be confusing in the README, since people may just strictly think about `O_APPEND`.

**Comment by lartaud** [comment]
I am talking about [os.Create](https://golang.org/pkg/os/#Create) ([source](https://golang.org/src/os/file.go?s=7623:7662#L248)), not `syscall.Creat` ;-p

And I confirm that `os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)` works correctly (even if `filename` already exists), whereas `os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)` doesn’t… (just tested…)

Regards

**Comment by xlucas** [comment]
Oh, allright.
